// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://whsmqfajrjcgqjsaaxxs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indoc21xZmFqcmpjZ3Fqc2FheHhzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIzMTc5NDYsImV4cCI6MjA1Nzg5Mzk0Nn0.GRRHVFxy3JGgSf0-uRK4n8U0sYXwl5_tYxUketh8oNo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);